### ISSUE TITLE
cromwellBase not changing

### ISSUE THREAD

**Issue by vortexing** [seandavi/cRomwell#7]
Hey, trying to use your package to interact with a cromwell server.  First things first, I can't seem to setCromwellBase to something that is anything else.  Thoughts?

R version 3.5.2 (2018-12-20), attached package: wdlRunR_0.5.0 

```
> setCromwellBase(base_url ='http://anythingelse:8000'); cromwellBase()
[1] "http://localhost:8000"
```

**Comment by seandavi** [comment]
Thanks for the report. The package has not gotten much love-and-care recently, so please keep the reports, questions, and experiences coming.

**Comment by vortexing** [comment]
Oh good!  Thanks for the fix.  In part, I wanted to post an issue to see if you were still up for maintenance/updates.  I'm working on a project using Cromwell and would love to interact with it via R, so beware what you wish for, I will ping you if I find things/have thoughts.  ;) Thanks for making this package though!  Seems less daunting if I don't have to start from scratch.

**Comment by seandavi** [comment]
I'd welcome any contribution you are willing to make, @vortexing.
